movieproject/movieapp/urls.py
from . import views
from django.urls import path

app_name = 'movieapp'

urlpatterns = [
    path('', views.index, name="index"),
    path("movie/<int:movie_id>/", views.detail, name="detail"),
    path("add/", views.add_movie, name="add"),
    path("update/<int:id>/", views.update_movie, name="update"),
    path("delete/<int:id>/", views.delete_movie, name="delete"),


    # path('', views.index, name="index"),
    # path('', views.base, name="base"),
    # path("movie/<int:movie_id>/", views.page2, name="page2"),
    # path("add/", views.page3, name="page3"),
    # path("update/<int:id>/", views.page4, name="update"),
    # path("delete/<int:id>/", views.page5, name="delete"),
    # path("movie/<int:movie_id>/", views.detail, name="detail"),
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models


# Create your models here.

class Movie(models.Model):
    name = models.CharField(max_length=250)
    director = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='movie')

    def __str__(self):
        return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie


class Movieform(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name', 'desc', 'img', 'year']

movieproject/movieapp/views.py
from django.shortcuts import render, redirect

from .forms import Movieform
from .models import Movie


def index(request):
    movies = Movie.objects.all()
    return render(request, "index.html", {'movie': movies})


def detail(request, movie_id):
    movie = Movie.objects.get(id=movie_id)
    return render(request, "detail.html", {'movie': movie})


def add_movie(request):
    if request.method == "POST":
        name = request.POST.get('name')
        desc = request.POST.get('desc')
        year = request.POST.get('year')
        img = request.FILES['img']
        movie = Movie(name=name, desc=desc, year=year, img=img)
        movie.save()
    return render(request, "add.html")


def update_movie(request, id):
    movie = Movie.objects.get(id=id)
    form = Movieform(request.POST or None, request.FILES or None, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')
    return render(request, "update.html", {'form': form, 'movie': movie})

def delete_movie(request, id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request, "delete.html")





    # def delete_movie(request, id):
    #     if request.method == 'POST':
    #         movie = Movie.objects.get(id=id)
    #         movie.delete()
    #         return redirect('/')
    #     return render(request, "delete.html")
# Create your views here.
# Fetch all datas from table
# def base(request):
#     movies = Movie.objects.all()
#     return render(request, "page1.html", {'movie': movies})
#
#
# # Fetch data from table using id
# def page2(request, movie_id):
#     movie = Movie. objects.get(id=movie_id)
#     return render(request, "page2.html", {'movie': movie})
#
#
# # Add new data to the table
# def page3(request):
#     if request.method == "POST":
#         name = request.POST.get('name')
#         desc = request.POST.get('desc')
#         year = request.POST.get('year')
#         img = request.FILES['img']
#         movie = Movie(name=name, desc=desc, year=year, img=img)
#         movie.save()
#     return render(request, "page3.html")
#
#
# # Update datas using id
# def page4(request, id):
#     movie = Movie.objects.get(id=id)
#     form = Movieform(request.POST or None, request.FILES or None, instance=movie)
#     if form.is_valid():
#         form.save()
#         return redirect('/')
#     return render(request, "page4.html", {'form': form, 'movie': movie})
#
#
# # delete data using id
# def page5(request, id):
#     if request.method == 'POST':
#         movie = Movie.objects.get(id=id)
#         movie.delete()
#         return redirect('/')
#     return render(request, "page5.html")

# def index(request):
#     movies = Movie.objects.all()
#     return render(request, "index.html", {'movie': movies})
#
#
# def detail(request, movie_id):
#     movie = Movie.objects.get(id=movie_id)
#     return render(request, "detail.html", {'movie': movie})

movieproject/templates/add.html
{% extends 'base.html'%}

{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <table>
    <tr><td><u><b>ADD NEW MOVIES</b></u></td></tr>
    <tr>
      <td style="padding:20px;">Enter Your Movie Name</td><td><input type="text" name="name" placeholder="Enter Your Movie Name"></td>
    </tr>
    <tr>
      <td style="padding:20px;">Enter the Movie Description</td><td><input type="text" name="desc" placeholder="Enter the Movie Description"></td>
    </tr>
    <tr>
      <td style="padding:20px;">Enter Your Movie Year</td><td><input type="text" name="year" placeholder="Enter Your Movie Year"></td>
    </tr>
    <tr>
      <td style="padding:20px;">Upload Image</td><td><input type="file" name="img" ></td>
    </tr>
    <tr>
      <td style="padding:20px;"></td><td><input type="submit"  ></td>
    </tr>
  </table>



</form>
{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Movies</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.3/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static 'style.css' %}" type="text/css" >
</head>
<body>

<div class="jumbotron text-center">
  <div style="float:left; padding-left:100px;">
   <img class="img1"  src="{% static 'R.png' %}">
  </div>
  <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="{% url 'movieapp:index' %}" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="{% url 'movieapp:add' %}" class="nav-link px-2 link-dark">Add New Movies</a></li>
  </ul>
</div>

<div class="container">
  <div class="row">
    {% block body%}
    {% endblock %}
  </div>
  </div>


</body>
</html>

movieproject/templates/detail.html
{% extends 'base.html'%}

{% block body %}
<div class="row">
  <h2>{{movie.name}}</h2>
  <hr>

  <div class="col-md-4">
    <img class="img2" src="{{ movie.img.url }}" alt=""><p></p>
    <h4>Director: {{ movie.director}}</h4><p></p>
    <h4>Year: {{movie.year}}</h4>
  </div>
  <div class="col-md-8">{{movie.desc}}
  <p><p>
    <a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">UPDATE</a>
    <a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">DELETE</a>
  </p>
  </div>

</div>
{% endblock %}

movieproject/templates/header.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style1.css' %}" type="text/css" >
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

movieproject/templates/index.html
{% extends 'base.html'%}

{% block body %}

{% for i in movie %}
<div class="col-sm-3">
    <a href="{% url 'movieapp:detail' i.id %}">
        <h3>{{ i.name }}</h3>
        <img class="img2" src="{{ i.img.url }}" alt="">
    </a>
    <a class="btn btn-danger" href="{% url 'todoapp:deletelist' i.id %}">Delete</a>
   <a class="btn btn-success" href="{% url 'todoapp:updatelist' i.id %}">Update</a>
</div>
{% endfor %}
{% endblock %}}

movieproject/templates/page1.html
{% extends 'header.html'%}

{% block body %}
{% for i in movie %}
<img  src="{{ i.img.url }}" alt="" width="100" height="100">
<a href="{% url 'movieapp:page2' i.id %}">
        {{ i.name }}<br>
    </a>
{% endfor %}
{% endblock %}

movieproject/templates/page2.html
{% extends 'header.html'%}

{% block body %}
<img  src="{{ movie.img.url }}" alt="" width="100" height="100">
{{movie.name}}<br>
{{movie.desc}}<br>
{{movie.year}}<br>

<a class="btn btn-warning" href="{% url 'movieapp:update' movie.id %}">UPDATE</a><br>
<a class="btn btn-danger" href="{% url 'movieapp:delete' movie.id %}">DELETE</a>

{% endblock %}

movieproject/templates/page3.html
{% extends 'header.html'%}

{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter Your Movie Name">
  <input type="text" name="desc" placeholder="Enter the Movie Description">
  <input type="text" name="year" placeholder="Enter Your Movie Year">
  <input type="file" name="img">
  <input type="submit">
</form>
{% endblock %}

movieproject/templates/page4.html
{% extends 'header.html'%}

{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/page5.html
{% extends 'header.html'%}

{% block body %}
<form method="post">
    {% csrf_token%}

    Are you want to delete this movie?
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/update.html
{% extends 'base.html'%}

{% block body %}
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
</form>
{% endblock %}